/* Sathya Bio storefront - Tamil (தமிழ்).
 *
 * keys:     for elements tagged data-i18n / data-i18n-placeholder and t() calls.
 * text:     gettext-style - the English text on the page is the key. Keys use
 *           single spaces; leading/trailing punctuation, emoji and symbols
 *           (e.g. "🌾 ", " *", "...", "?") are kept from the page and need
 *           not be part of the key.
 * patterns: English text with numbers or names in it.
 *
 * Loaded before app.js. Product names, brand names and farmer testimonials
 * are left as written.
 */
window.SB_LANG_TA = {
  keys: {
    topbar_shipping: '₹999-க்கு மேல் ஆர்டர்களுக்கு இலவச டெலிவரி',
    logo_sub: 'வேளாண் பூச்சிக்கொல்லி அங்காடி',
    search_placeholder: 'பயிர், நோய் அல்லது மருந்து பெயரில் தேடுங்கள்...',
    search_btn: 'தேடு',
    basket_label: 'கூடை',
    nav_all_products: 'அனைத்து பொருட்கள்',
    hero_title: 'உங்கள் பயிர்களைப் பாதுகாக்கவும்.\nவிளைச்சலை அதிகரிக்கவும்.',
    hero_desc: '100% உயிர்ச் சான்று பெற்ற பூஞ்சைக்கொல்லிகள், பூச்சிக்கொல்லிகள் மற்றும் மண் வளப் பொருட்களை ஆன்லைனில் ஆர்டர் செய்யுங்கள். நேரடி விரைவு டெலிவரி.',
    // Hero buttons share one row on a phone; longer labels stacked them and
    // overflowed the banner.
    hero_shop_btn: 'பொருட்கள்',
    hero_soil_btn: 'மண் அறிக்கை',
    trust_certified: '100% சான்றளிக்கப்பட்ட தரம்',
    trust_dispatch: 'அதே நாளில் அனுப்புதல்',
    trust_whatsapp: 'வாட்ஸ்அப் உதவி',
    shop_by_category: 'வகை வாரியாக வாங்குங்கள்',
    catalog_title: 'வேளாண் பூச்சிக்கொல்லி பொருட்கள் பட்டியல்',
    catalog_subtitle: 'பயிர், தாவர நோய் அல்லது பொருள் வகை வாரியாக வடிகட்டுங்கள்',
    filter_title: 'வடிகட்டிகள்',
    filter_crop: 'பயிர் வாரியாக',
    filter_disease: 'நோய் / பூச்சி வாரியாக',
    filter_category: 'வகை',
    reset_filters: 'வடிகட்டிகளை நீக்கு',
    // Sits beside a cart icon in a narrow two-column card button.
    add_to_cart: 'சேர்',
    reviews: 'மதிப்புரைகள்',
    soil_title: 'மண் பரிசோதனை அறிக்கை ஆய்வு',
    soil_desc: 'உங்கள் ஆய்வக மண் பரிசோதனை ஆவணத்தை (PDF அல்லது படம்) பதிவேற்றுங்கள். எங்கள் AI நைட்ரஜன், பாஸ்பரஸ், பொட்டாசியம் அளவுகளைப் படித்து, ஏற்ற சத்யா பயோ உயிர் ஊக்கிகளைப் பரிந்துரைக்கும்.',
    soil_upload_btn: 'மண் அறிக்கை பதிவேற்று',
    soil_dropzone: 'மண் ஆவணத்தை இங்கே இழுத்து விடுங்கள்',
    soil_formats: 'PDF, PNG, JPG ஏற்கப்படும்',
    n8n_title: 'வாட்ஸ்அப் N8N தானியங்கி உதவியாளர்',
    n8n_subtitle: 'N8N தானியங்கி பணிப்பாய்வுகள் வாட்ஸ்அப் வழியாக விவசாயிகளுக்கு 24/7 எப்படி உதவுகின்றன என்று பாருங்கள்',
    n8n_test_btn: 'N8N சோதனையை இயக்கு',
    tickets_title: 'உதவி கோரிக்கை அமைப்பு',
    tickets_subtitle: 'வயல் தொழில்நுட்ப உதவி & மருந்து அளவு சந்தேகங்கள்',
    ticket_new_btn: 'கோரிக்கை அனுப்பு',
    experts_title: 'தாவர மருத்துவ நிபுணருடன் இணையுங்கள்',
    experts_subtitle: 'மூத்த வேளாண் விஞ்ஞானிகளுடன் நேரடி ஆலோசனை அழைப்புகள்',
    footer_nav: 'பொருள் வகைகள்',
    footer_crops: 'முக்கிய பயிர்கள்',
    footer_help: 'வாடிக்கையாளர் உதவி',
    footer_copyright: '© 2026 சத்யா பயோ அக்ரோ டெக் லிமிடெட். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    chatbot_title: 'சத்யா பயோ உரையாடல் உதவியாளர்',
    chat_placeholder: 'பயிர் கேள்வியைத் தட்டச்சு செய்யுங்கள்...',
    chat_welcome: '👋 சத்யா பயோ வேளாண் உதவிக்கு வரவேற்கிறோம்! இன்று உங்கள் பயிருக்கு எப்படி உதவலாம்?',
    checkout_title: 'உங்கள் ஆர்டரை முடிக்கவும்',
    field_name: 'முழுப் பெயர்',
    field_phone: 'மொபைல் எண் (வாட்ஸ்அப் தகவல்களுக்கு)',
    field_address: 'பண்ணை டெலிவரி முகவரி',
    field_payment: 'பணம் செலுத்தும் முறை',
    pay_cod: 'டெலிவரியின் போது பணம் (COD)',
    pay_upi: 'UPI / கூகுள் பே / போன்பே',
    pay_bank: 'நெட் பேங்கிங் / KCC அட்டை',
    place_order: 'இப்போதே ஆர்டர் செய்',
    scan_title: 'AI பயிர் நோய் புகைப்பட ஸ்கேனர்',
    scan_desc: 'AI நோயைக் கண்டறிந்து ஏற்ற மருந்தைப் பரிந்துரைக்கும்',
    advisory_label: 'கணக்கு',
    lang_label: 'மொழி',
    showing_products: 'காட்டப்படுவது',
    of_products: '/',
    products_label: 'பொருட்கள்',
    nav_ai_scanner: 'AI இலை மருத்துவர்'
  },

  text: {
    // Ticker
    'FLAT 15% OFF on first order — Use code': 'முதல் ஆர்டருக்கு 15% தள்ளுபடி — குறியீடு',
    'Free express delivery on orders above ₹999 across all 28 states': '28 மாநிலங்களிலும் ₹999-க்கு மேல் ஆர்டர்களுக்கு இலவச விரைவு டெலிவரி',
    'BlastShield 75 WP — #1 Selling Paddy Fungicide this Kharif Season': 'BlastShield 75 WP — இந்த காரீஃப் பருவத்தின் #1 நெல் பூஞ்சைக்கொல்லி',
    'WhatsApp us at 9000-425-999 for instant crop advisory in your language': 'உங்கள் மொழியில் உடனடி பயிர் ஆலோசனைக்கு 9000-425-999 எண்ணில் வாட்ஸ்அப் செய்யுங்கள்',
    'Sathya Bio — Winner of ICAR Best AgriTech 2025 Award': 'சத்யா பயோ — ICAR சிறந்த வேளாண் தொழில்நுட்ப விருது 2025',
    'Missed Call To Order': 'ஆர்டர் செய்ய மிஸ்டு கால்',
    '24 hrs, 7 days': '24 மணி நேரம், 7 நாட்கள்',

    // Header & navigation
    'Categories': 'வகைகள்',
    'Shop by Crop': 'பயிர் வாரியாக வாங்க',
    'Brands': 'பிராண்டுகள்',
    'Soil Analyzer': 'மண் ஆய்வு',
    'Support Tickets': 'உதவி கோரிக்கைகள்',
    'Agronomists': 'வேளாண் நிபுணர்கள்',
    'Track': 'கண்காணி',
    'Order Status': 'ஆர்டர் நிலை',
    'Saved': 'சேமித்தவை',
    'Wishlist': 'விருப்பப் பட்டியல்',
    'Sign In / Register': 'உள்நுழை / பதிவு',
    'Account': 'கணக்கு',

    // Hero
    "India's #1 Bio-Pesticide Store": 'இந்தியாவின் #1 உயிர் மருந்துக் கடை',
    'AI Soil Engine': 'AI மண் ஆய்வு',
    'Soil Report Analyzer': 'மண் அறிக்கை ஆய்வு',
    'Upload lab PDF & get N-P-K nutrient remedies': 'ஆய்வக PDF-ஐப் பதிவேற்றி N-P-K சத்துத் தீர்வுகளைப் பெறுங்கள்',
    'Instant Diagnostic': 'உடனடி பரிசோதனை',
    'AI Leaf Scanner': 'AI இலை ஸ்கேனர்',
    'Upload leaf photo for 10-second disease check': 'இலைப் படத்தைப் பதிவேற்றி 10 விநாடியில் நோயைக் கண்டறியுங்கள்',
    '24/7 WhatsApp AI': '24/7 வாட்ஸ்அப் AI',
    'Automated Field Assistant': 'தானியங்கி வயல் உதவியாளர்',
    'Get instant pesticide dosage guides & disease remedies directly on WhatsApp': 'மருந்து அளவு வழிகாட்டிகளையும் நோய்த் தீர்வுகளையும் வாட்ஸ்அப்பில் உடனே பெறுங்கள்',

    // Deal banner
    'Kharif Season Sale — Up to 30% Off Paddy & Cotton Essentials': 'காரீஃப் பருவ விற்பனை — நெல் & பருத்திப் பொருட்களுக்கு 30% வரை தள்ளுபடி',
    'Limited stock. Ends midnight tonight. COD available': 'குறைந்த இருப்பு. இன்று நள்ளிரவு வரை மட்டும். COD வசதி உண்டு',
    'Ends in': 'முடிவடைய',
    'hrs': 'மணி',
    'min': 'நிமி',
    'sec': 'வினா',
    'Shop Now': 'இப்போதே வாங்கு',

    // Trust strip & stats
    'Lab-Tested Original Bio-Formulations': 'ஆய்வகச் சோதனை செய்த அசல் உயிர் மருந்துகள்',
    'Express Doorstep Delivery Across India': 'இந்தியா முழுவதும் வீட்டு வாசலுக்கு விரைவு டெலிவரி',
    'Cash On Delivery': 'டெலிவரியின் போது பணம்',
    'Pay After Delivery at Your Farm': 'பொருள் பண்ணைக்கு வந்த பிறகு பணம் செலுத்துங்கள்',
    '24/7 Advisory from Senior Agronomists': 'மூத்த வேளாண் நிபுணர்களின் 24/7 ஆலோசனை',
    'Farmers Served': 'பயனடைந்த விவசாயிகள்',
    'across 18 Indian states': '18 இந்திய மாநிலங்களில்',
    'Product Formulations': 'மருந்து வகைகள்',
    '100% bio-certified lab tested': '100% உயிர்ச் சான்று, ஆய்வகச் சோதனை',
    'Dispatch Rate': 'அனுப்புதல் விகிதம்',
    'same-day orders fulfilled': 'அதே நாளில் அனுப்பிய ஆர்டர்கள்',
    'Years of Expertise': 'ஆண்டு அனுபவம்',
    'trusted since 2013': '2013 முதல் நம்பிக்கை',

    // Shop by category
    'Explore crop protection chemicals, bio-stimulants, and soil nutrients': 'பயிர் பாதுகாப்பு மருந்துகள், உயிர் ஊக்கிகள் மற்றும் மண் சத்துகளைப் பாருங்கள்',
    'Crop Disease Defense': 'பயிர் நோய்த் தடுப்பு',
    'Fungicides': 'பூஞ்சைக்கொல்லிகள்',
    'Cure Blast, Blight, Powdery Mildew & Rust': 'குலை நோய், கருகல், சாம்பல் நோய் & துரு நோயைக் கட்டுப்படுத்தும்',
    'Pest Protection': 'பூச்சிப் பாதுகாப்பு',
    'Insecticides': 'பூச்சிக்கொல்லிகள்',
    'Control Whitefly, Bollworm, Aphids & Borer': 'வெள்ளை ஈ, காய்ப்புழு, அசுவினி & துளைப்பானைக் கட்டுப்படுத்தும்',
    'Yield Booster': 'விளைச்சல் ஊக்கி',
    'Bio-Stimulants': 'உயிர் ஊக்கிகள்',
    'Root Vigor, Flowering & Fruit Mass Booster': 'வேர் வளர்ச்சி, பூத்தல் & காய் பருமனை அதிகரிக்கும்',
    'Weed Elimination': 'களை ஒழிப்பு',
    'Herbicides': 'களைக்கொல்லிகள்',
    'Selective Pre & Post Emergence Weed Control': 'முளைப்பதற்கு முன்னும் பின்னும் தேர்ந்த களைக் கட்டுப்பாடு',
    'Soil Protection': 'மண் பாதுகாப்பு',
    'Nematicides': 'நூற்புழுக்கொல்லிகள்',
    'Protect Roots Against Nematode Attacks': 'நூற்புழுத் தாக்குதலிலிருந்து வேர்களைக் காக்கும்',
    'Full Catalog': 'முழுப் பட்டியல்',
    'All 35 Agro Formulations': 'அனைத்து 35 வேளாண் மருந்துகள்',
    'Browse complete Sathya Bio product range': 'சத்யா பயோவின் அனைத்துப் பொருட்களையும் பாருங்கள்',
    'Fungicide': 'பூஞ்சைக்கொல்லி',
    'Insecticide': 'பூச்சிக்கொல்லி',
    'Herbicide': 'களைக்கொல்லி',
    'Bio-Stimulant': 'உயிர் ஊக்கி',
    'Nematicide': 'நூற்புழுக்கொல்லி',
    'Bio-Fungicides': 'உயிர் பூஞ்சைக்கொல்லிகள்',

    // Shop by crop
    'Select your crop to get customized pesticide & nutrient recommendations': 'உங்கள் பயிரைத் தேர்ந்தெடுத்து ஏற்ற மருந்து & சத்துப் பரிந்துரைகளைப் பெறுங்கள்',
    'Blast Defense': 'குலை நோய்த் தடுப்பு',
    'Paddy / Rice': 'நெல் / அரிசி',
    'Paddy/Rice': 'நெல்/அரிசி',
    'Whitefly Shield': 'வெள்ளை ஈ தடுப்பு',
    'Cotton': 'பருத்தி',
    'Blight Care': 'கருகல் நோய்ப் பராமரிப்பு',
    'Tomato': 'தக்காளி',
    'Rust Control': 'துரு நோய்க் கட்டுப்பாடு',
    'Wheat': 'கோதுமை',
    'Borer Solution': 'துளைப்பான் தீர்வு',
    'Sugarcane': 'கரும்பு',
    'Armyworm Defense': 'படைப்புழுத் தடுப்பு',
    'Corn / Maize': 'மக்காச்சோளம்',
    'Mildew Protect': 'சாம்பல் நோய்ப் பாதுகாப்பு',
    'Grapes': 'திராட்சை',
    'Grapes / Fruits': 'திராட்சை / பழங்கள்',
    'Tuber Guard': 'கிழங்குப் பாதுகாப்பு',
    'Potato': 'உருளைக்கிழங்கு',
    'Fruits': 'பழங்கள்',
    'All Crops': 'அனைத்துப் பயிர்கள்',
    'Certifications & Recognitions': 'சான்றிதழ்கள் & அங்கீகாரங்கள்',

    // Catalog
    'All': 'அனைத்தும்',
    'Filters & Sort': 'வடிகட்டிகள்',
    'Filter & Sort Products': 'பொருட்களை வடிகட்டு & வரிசைப்படுத்து',
    'Reset': 'மீட்டமை',
    'Apply Filters': 'வடிகட்டிகளைப் பயன்படுத்து',
    'Showing products': 'பொருட்கள் ஏற்றப்படுகின்றன',
    'Trending & Related Products': 'பிரபலமான & தொடர்புடைய பொருட்கள்',
    'Recommended products based on current crop seasonal demand': 'தற்போதைய பருவத் தேவைக்கேற்ப பரிந்துரைக்கப்பட்ட பொருட்கள்',
    'No verified reviews yet': 'இன்னும் சரிபார்த்த மதிப்புரைகள் இல்லை',
    'Special Offer': 'சிறப்புச் சலுகை',
    'Recommended for You': 'உங்களுக்கான பரிந்துரை',
    'No products found': 'பொருட்கள் எதுவும் இல்லை',
    'Try adjusting crop or disease filters': 'பயிர் அல்லது நோய் வடிகட்டிகளை மாற்றிப் பாருங்கள்',

    // Soil, N8N, tickets, experts
    'N8N Workflow Graph': 'N8N பணிப்பாய்வு வரைபடம்',
    'Test N8N Webhook Agent': 'N8N வெப்ஹூக் சோதனை',
    'WhatsApp Webhook': 'வாட்ஸ்அப் வெப்ஹூக்',
    'Receives farmer incoming message & photo': 'விவசாயியின் செய்தி & படத்தைப் பெறுகிறது',
    'AI Disease Parser': 'AI நோய்ப் பகுப்பாய்வு',
    'Extracts crop type & symptoms': 'பயிர் வகை & அறிகுறிகளைக் கண்டறிகிறது',
    'Catalog Lookup DB': 'பொருள் பட்டியல் தேடல்',
    'Matches exact fungicide remedy': 'சரியான பூஞ்சைக்கொல்லித் தீர்வைப் பொருத்துகிறது',
    'WhatsApp Response': 'வாட்ஸ்அப் பதில்',
    'Sends instant dosage & order button': 'மருந்து அளவு & ஆர்டர் பொத்தானை உடனே அனுப்புகிறது',
    'Success': 'வெற்றி',
    'Ready': 'தயார்',
    'In Progress': 'நடைபெறுகிறது',
    'Resolved': 'தீர்க்கப்பட்டது',
    'Open': 'திறந்துள்ளது',
    'Leaf Yellowing & Stunting in Paddy Field': 'நெல் வயலில் இலை மஞ்சளாதல் & வளர்ச்சிக் குறைவு',
    'Chief Agronomist & Soil Pathology Lead': 'தலைமை வேளாண் நிபுணர் & மண் நோயியல் தலைவர்',
    'Senior Crop Protection Specialist': 'மூத்த பயிர் பாதுகாப்பு நிபுணர்',
    'Book Consultation': 'ஆலோசனை பதிவு செய்',

    // Testimonials & newsletter
    'Trusted by 15,000+ Indian Farmers': '15,000+ இந்திய விவசாயிகளின் நம்பிக்கை',
    'Real results from paddy, cotton, tomato, and fruit growers': 'நெல், பருத்தி, தக்காளி, பழ விவசாயிகளின் உண்மையான அனுபவங்கள்',
    'Free Seasonal Advisory': 'இலவசப் பருவ ஆலோசனை',
    'Get Weekly Crop & Pesticide': 'வாராந்திர பயிர் & மருந்துப்',
    'Recommendations': 'பரிந்துரைகளைப் பெறுங்கள்',
    'Join 15,000+ farmers receiving our free seasonal advisory newsletter. Kharif & Rabi crop schedules, disease alerts, and exclusive offers every week': 'எங்கள் இலவசப் பருவ ஆலோசனைச் செய்திமடலைப் பெறும் 15,000+ விவசாயிகளுடன் இணையுங்கள். காரீஃப் & ராபி பயிர் அட்டவணைகள், நோய் எச்சரிக்கைகள், சிறப்புச் சலுகைகள் ஒவ்வொரு வாரமும்',
    'Enter your WhatsApp Number': 'உங்கள் வாட்ஸ்அப் எண்ணை உள்ளிடுங்கள்',
    'Paddy / Rice Farmer': 'நெல் விவசாயி',
    'Cotton Farmer': 'பருத்தி விவசாயி',
    'Horticulture / Vegetables': 'தோட்டக்கலை / காய்கறிகள்',
    'Sugarcane Farmer': 'கரும்பு விவசாயி',
    'Mixed Crop Farmer': 'கலப்புப் பயிர் விவசாயி',
    'Subscribe Free': 'இலவசமாகப் பதிவு செய்',
    'No spam. Unsubscribe anytime. Available in 6 South Indian languages': 'தேவையற்ற செய்திகள் இல்லை. எப்போது வேண்டுமானாலும் விலகலாம். 6 தென்னிந்திய மொழிகளில் கிடைக்கும்',

    // Footer
    "Sathya Bio is India's leading digital platform for high-efficacy bio-pesticides, crop protection chemicals, and soil health fertilizers. Providing 100% bio-certified products with fast express dispatch to 15,000+ farmers across India": 'சத்யா பயோ, உயர் திறன் கொண்ட உயிர் பூச்சிக்கொல்லிகள், பயிர் பாதுகாப்பு மருந்துகள் மற்றும் மண் வள உரங்களுக்கான இந்தியாவின் முன்னணி டிஜிட்டல் தளம். இந்தியா முழுவதும் 15,000+ விவசாயிகளுக்கு 100% உயிர்ச் சான்று பெற்ற பொருட்களை விரைவாக அனுப்புகிறோம்',
    'Paddy / Rice Care': 'நெல் பராமரிப்பு',
    'Cotton Protection': 'பருத்திப் பாதுகாப்பு',
    'Tomato & Vegetables': 'தக்காளி & காய்கறிகள்',
    'Sugarcane Care': 'கரும்புப் பராமரிப்பு',
    'Horticulture & Fruits': 'தோட்டக்கலை & பழங்கள்',
    'Toll Free: 1800-425-9999': 'கட்டணமில்லா எண்: 1800-425-9999',
    'Sathya Bio Tech Park, Hyderabad, India': 'சத்யா பயோ டெக் பார்க், ஹைதராபாத், இந்தியா',
    '100% Secure Payment (UPI, COD, NetBanking)': '100% பாதுகாப்பான பணப்பரிவர்த்தனை (UPI, COD, நெட் பேங்கிங்)',
    'Privacy Policy': 'தனியுரிமைக் கொள்கை',
    'Terms of Sale': 'விற்பனை விதிமுறைகள்',
    'Refund Policy': 'பணத்திருப்பக் கொள்கை',

    // Basket
    'Your Basket': 'உங்கள் கூடை',
    'Subtotal': 'கூட்டுத்தொகை',
    'Delivery': 'டெலிவரி',
    'FREE': 'இலவசம்',
    'Total': 'மொத்தம்',
    'Checkout': 'பணம் செலுத்த',
    'Secure payment · UPI, cards or cash on delivery': 'பாதுகாப்பான பணப்பரிவர்த்தனை · UPI, அட்டைகள் அல்லது டெலிவரியின் போது பணம்',
    'Your basket is empty': 'உங்கள் கூடை காலியாக உள்ளது',
    'Add crop protection products to get started': 'தொடங்க பயிர் பாதுகாப்புப் பொருட்களைச் சேர்க்கவும்',
    'Browse products': 'பொருட்களைப் பார்க்க',
    'Your basket is empty. Add products from the catalog first': 'உங்கள் கூடை காலியாக உள்ளது. முதலில் பட்டியலிலிருந்து பொருட்களைச் சேர்க்கவும்',

    // Popups: scanner, soil, ticket, expert, chat
    'Take or upload a leaf photo': 'இலைப் படம் எடுக்கவும் அல்லது பதிவேற்றவும்',
    'JPG or PNG · a clear, close-up photo': 'JPG அல்லது PNG · தெளிவான, அருகில் எடுத்த படம்',
    'Diagnose Crop Disease': 'பயிர் நோயைக் கண்டறி',
    'Upload your soil PDF/image to automatically receive recommended Sathya Bio bio-stimulants': 'உங்கள் மண் PDF/படத்தைப் பதிவேற்றி, பரிந்துரைக்கப்பட்ட சத்யா பயோ உயிர் ஊக்கிகளைத் தானாகப் பெறுங்கள்',
    'Analyze Soil Report': 'மண் அறிக்கையை ஆய்வு செய்',
    'Submit Field Advisory Ticket': 'வயல் ஆலோசனைக் கோரிக்கை அனுப்பு',
    'Subject (e.g., Leaf yellowing in paddy)': 'தலைப்பு (எ.கா., நெல்லில் இலை மஞ்சளாதல்)',
    'Field Advisory': 'வயல் ஆலோசனை',
    'Product Dosage': 'மருந்து அளவு',
    'Order Delivery Query': 'ஆர்டர் டெலிவரி சந்தேகம்',
    'Describe crop symptoms': 'பயிர் அறிகுறிகளை விவரிக்கவும்',
    'Submit Ticket': 'கோரிக்கை அனுப்பு',
    'Book Agronomist Call': 'வேளாண் நிபுணர் அழைப்பைப் பதிவு செய்',
    'Your Name & Phone Number': 'உங்கள் பெயர் & தொலைபேசி எண்',
    'Paddy & Grain Diseases Expert': 'நெல் & தானிய நோய் நிபுணர்',
    'Cotton Whitefly Specialist': 'பருத்தி வெள்ளை ஈ நிபுணர்',
    'Soil & Fertigation Agronomist': 'மண் & உரப்பாசன வேளாண் நிபுணர்',
    'Confirm Consultation': 'ஆலோசனையை உறுதிசெய்',
    '● Online 24/7 (Instant Response)': '● 24/7 இணைப்பில் (உடனடி பதில்)',
    'Paddy Blast Remedy': 'நெல் குலை நோய்த் தீர்வு',
    'Cotton Whitefly': 'பருத்தி வெள்ளை ஈ',
    'Soil Test Guide': 'மண் பரிசோதனை வழிகாட்டி',
    'Call Agronomist': 'வேளாண் நிபுணரை அழை',

    // Welcome poster
    'Agro Pesticides & Crop Advisory': 'வேளாண் மருந்துகள் & பயிர் ஆலோசனை',
    'We Care For You': 'உங்கள் மீது அக்கறை கொள்கிறோம்',
    'Farmer Advisory Platform': 'விவசாயி ஆலோசனைத் தளம்',
    'Welcome to the Personalized Farming Experience': 'தனிப்பயன் விவசாய அனுபவத்திற்கு வரவேற்கிறோம்',
    'Welcome to the personalized farming experience that you can do farming with our expert with daily updates. We care for you': 'எங்கள் நிபுணர்களின் தினசரி வழிகாட்டுதலுடன் விவசாயம் செய்யும் தனிப்பயன் அனுபவத்திற்கு வரவேற்கிறோம். உங்கள் மீது அக்கறை கொள்கிறோம்',
    'Direct 1-on-1 Agronomist Consultations': 'வேளாண் நிபுணருடன் நேரடி தனிப்பட்ட ஆலோசனை',
    'Daily Crop Protection & Disease Updates': 'தினசரி பயிர் பாதுகாப்பு & நோய்த் தகவல்கள்',
    '100% Bio-Certified Formulations': '100% உயிர்ச் சான்று பெற்ற மருந்துகள்',
    'Connect With Expert': 'நிபுணருடன் இணையுங்கள்',
    'Explore': 'பார்வையிடு',

    // Sign in, register, forgot password
    'Login or Sign Up is mandatory to access your basket and checkout': 'கூடையைப் பார்க்கவும் ஆர்டர் செய்யவும் உள்நுழைவு அல்லது பதிவு அவசியம்',
    'Sign In': 'உள்நுழை',
    'New Farmer': 'புதிய விவசாயி',
    'Welcome to Sathya Bio': 'சத்யா பயோவுக்கு வரவேற்கிறோம்',
    'Sign in to access personalized crop protection & exclusive farm deals': 'தனிப்பயன் பயிர் பாதுகாப்பு & சிறப்புச் சலுகைகளைப் பெற உள்நுழையுங்கள்',
    'Mobile Number or Email': 'மொபைல் எண் அல்லது மின்னஞ்சல்',
    'Password': 'கடவுச்சொல்',
    'Enter password': 'கடவுச்சொல்லை உள்ளிடுங்கள்',
    'Forgot password': 'கடவுச்சொல் மறந்துவிட்டதா',
    'Sign In to Sathya Bio': 'சத்யா பயோவில் உள்நுழை',
    'Create Farmer Account': 'விவசாயி கணக்கை உருவாக்கு',
    'Join 15,000+ farmers for customized pesticides & advisories': 'தனிப்பயன் மருந்துகள் & ஆலோசனைகளுக்கு 15,000+ விவசாயிகளுடன் இணையுங்கள்',
    'Full Farmer Name': 'விவசாயியின் முழுப் பெயர்',
    'Mobile Number': 'மொபைல் எண்',
    '10 Digit Number': '10 இலக்க எண்',
    '8+ characters: letters & numbers': '8+ எழுத்துகள்: எழுத்துகள் & எண்கள்',
    'Primary Crop': 'முதன்மைப் பயிர்',
    'Land Size': 'நில அளவு',
    'Acres': 'ஏக்கர்',
    'Village / Farm Address': 'கிராமம் / பண்ணை முகவரி',
    'Register & Access Deals': 'பதிவு செய்து சலுகைகளைப் பெறுக',
    'Back to sign in': 'உள்நுழைவுக்குத் திரும்பு',
    'Reset your password': 'கடவுச்சொல்லை மீட்டமை',
    "Enter your registered mobile number. We'll send a 6-digit code to its WhatsApp": 'பதிவு செய்த மொபைல் எண்ணை உள்ளிடுங்கள். அதன் வாட்ஸ்அப்பிற்கு 6 இலக்கக் குறியீட்டை அனுப்புவோம்',
    'Registered mobile number': 'பதிவு செய்த மொபைல் எண்',
    '10-digit mobile number': '10 இலக்க மொபைல் எண்',
    'Send reset code': 'மீட்டமைப்புக் குறியீட்டை அனுப்பு',
    '6-digit code': '6 இலக்கக் குறியீடு',
    'Code sent on WhatsApp': 'வாட்ஸ்அப்பில் குறியீடு அனுப்பப்பட்டது',
    "Didn't get it": 'கிடைக்கவில்லையா',
    'Resend code': 'மீண்டும் அனுப்பு',
    'New password': 'புதிய கடவுச்சொல்',
    'Confirm new password': 'புதிய கடவுச்சொல்லை உறுதிசெய்',
    'Type it again': 'மீண்டும் தட்டச்சு செய்யுங்கள்',
    'Reset password & sign in': 'கடவுச்சொல்லை மீட்டமைத்து உள்நுழை',
    'Use a different number': 'வேறு எண்ணைப் பயன்படுத்து',
    'At least 8 characters': 'குறைந்தது 8 எழுத்துகள்',
    'At least one letter (a-z)': 'குறைந்தது ஒரு எழுத்து (a-z)',
    'At least one number (0-9)': 'குறைந்தது ஒரு எண் (0-9)',
    'Not a common password or your mobile number': 'பொதுவான கடவுச்சொல் அல்லது உங்கள் மொபைல் எண் கூடாது',
    'Passwords do not match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'Enter your 10-digit registered mobile number': 'உங்கள் 10 இலக்கப் பதிவு மொபைல் எண்ணை உள்ளிடுங்கள்',
    'Enter the 6-digit code from WhatsApp': 'வாட்ஸ்அப்பில் வந்த 6 இலக்கக் குறியீட்டை உள்ளிடுங்கள்',
    'Your new password does not meet all the rules above': 'புதிய கடவுச்சொல் மேலே உள்ள அனைத்து விதிகளையும் பூர்த்தி செய்யவில்லை',
    'If this number is registered with Sathya Bio, a 6-digit reset code has been sent to its WhatsApp': 'இந்த எண் சத்யா பயோவில் பதிவு செய்யப்பட்டிருந்தால், அதன் வாட்ஸ்அப்பிற்கு 6 இலக்க மீட்டமைப்புக் குறியீடு அனுப்பப்பட்டுள்ளது',
    'Your password has been reset. You are now signed in': 'உங்கள் கடவுச்சொல் மீட்டமைக்கப்பட்டது. நீங்கள் இப்போது உள்நுழைந்துள்ளீர்கள்',

    // Signed-in view
    'Mobile': 'மொபைல்',
    'Crop & Acreage': 'பயிர் & ஏக்கர்',
    'Location': 'இடம்',
    'Catalog Personalization': 'பட்டியல் தனிப்பயனாக்கம்',
    'Active': 'செயலில்',
    'Open Admin Panel': 'நிர்வாகப் பலகையைத் திற',
    'Sign Out': 'வெளியேறு',

    // Menu sheet
    'Sign in to track orders & get crop advice': 'ஆர்டர்களைக் கண்காணிக்கவும் பயிர் ஆலோசனை பெறவும் உள்நுழையுங்கள்',
    'Quick actions': 'விரைவுச் செயல்கள்',
    'All Products': 'அனைத்து பொருட்கள்',
    'AI Leaf Doctor': 'AI இலை மருத்துவர்',
    'Track Order': 'ஆர்டரைக் கண்காணி',
    'Support': 'உதவி',
    'WhatsApp Expert': 'வாட்ஸ்அப் நிபுணர்',
    'Shop by category': 'வகை வாரியாக வாங்க',
    'Shop by crop': 'பயிர் வாரியாக வாங்க',

    // Bottom bar
    'Home': 'முகப்பு',
    'Shop': 'கடை',
    // Short on purpose: the tab is ~64px wide and its camera icon already says "scan".
    'AI Doctor': 'மருத்துவர்',
    'Cart': 'கூடை',
    'Menu': 'மெனு'
  },

  patterns: [
    [/^(\d+) items?$/, '$1 பொருட்கள்'],
    [/^(\d+) Products$/, '$1 பொருட்கள்'],
    [/^(\d+)% OFF$/i, '$1% தள்ளுபடி'],
    [/^(₹[\d,]+) each$/, 'ஒன்றுக்கு $1'],
    [/^Tailored for (.+)$/, '$1 பயிருக்கு ஏற்றது'],
    [/^([\d.]+ ★) \((\d+)\+ Calls$/, '$1 ($2+ அழைப்புகள்'],
    [/^Resend in (\d+)s$/, '$1 வினாடியில் மீண்டும் அனுப்பலாம்'],
    [/^Please wait (\d+) seconds before requesting another code$/, 'மற்றொரு குறியீடு கேட்க $1 வினாடிகள் காத்திருக்கவும்'],
    [/^Enter the code sent to WhatsApp on \+91 (\d{10}), then choose a new password$/, '+91 $1 வாட்ஸ்அப்பிற்கு அனுப்பிய குறியீட்டை உள்ளிட்டு, புதிய கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும்']
  ]
};
